Slicing in Python is a method for extracting specific portions of sequences like strings, lists, tuples, and ranges. Slicing can refer to using the built-in slice() function or the even more common bracket notation that looks like this: [start:end:step]. The functionality is a core part of the Python language, so you can perform slicing with or without importing any additional packages. 

In [4]:
numbers = [10, 20, 30, 40, 50, 60]

# from 1st index to 3rd (4th excluded)
print(numbers[1:4])

# from 0 to 2 (3rd index excluded)
print(numbers[:3])

print(numbers[::2])

[20, 30, 40]
[10, 20, 30]
[10, 30, 50]


In [ ]:
# String Slicings
text = "Python Slicing"

print(text[7:])

# start slicing from the last element or index
print(text[::-1])

Slicing
gnicilS nohtyP


In [ ]:
# Using a Slice function: slice()
slice_obj = slice(1, 4)

numbers = [10, 20, 30, 40, 50]
print(numbers[slice_obj])

# Apply to a string
text = "Python"

# grabs elements from index 1 upto 3
print(text[slice_obj])

[20, 30, 40]
yth


In [10]:
# Slicing in Numpy
import numpy as np

# Create a 1D array
array = np.array([10, 20, 30, 40, 50])

# Slice elements from index 1 to 3
print(array[1:4])

# Print Array
print(array)

[20 30 40]
[10 20 30 40 50]


In [25]:
# Create a 2D array
array_2d = np.array(
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ]
)

# Slice the first two rows and first two columns
print(array_2d[:2, :2])

print(" --------------- ")

# Slice the last column
print(array_2d[:, -1])

[[1 2]
 [4 5]]
 --------------- 
[3 6 9]


In [32]:
# Slicing in Pandas
import pandas as pd

# Create a sample DataFrame
student_data = {
  'Name': ['Alice', 'Bob', 'Charlie'],
  'Age': [25, 30, 35],
  'Score': [85, 90, 95]
}

students = pd.DataFrame(student_data)

# Take a look at how data frame is created here
print(students)

print("---------- ------------- -------------")

# Slice the first two rows
print(students[:2])

print("---------- ------------- -------------")

# Slice specific columns by name
print(students[ ['Name', 'Score'] ])

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
---------- ------------- -------------
    Name  Age  Score
0  Alice   25     85
1    Bob   30     90
---------- ------------- -------------
      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     95


.loc[] and .iloc[] for better control. .loc is for label-based and .iloc is for index based.
Let's see coding examples for this.

In [37]:
# First check our dataframe students
print(students)

print("---------- ------------- -------------")

# Slice using .iloc 
# 1: --> specifies that select all columns starting from index 1 to the end of the dataframe.
# 1: --> after comma, this specifies that select all rows starting from index 1 to the end of the dataframe.
print(students.iloc[1:, 1:])

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
---------- ------------- -------------
   Age  Score
1   30     90
2   35     95


In [39]:
# Slice using .loc (label-based)

# :1 --> include rows from 0 to 1 (inclusive)
print(students.loc[:1, ['Name', 'Age']])

    Name  Age
0  Alice   25
1    Bob   30


In [40]:
# Slicing in Tuples 
# Tuples are immutable, but slicing still works

# Tuple is created using brackets ()
colors = ("red", "green", "blue", "yellow")

print(colors[:2])

('red', 'green')


In [43]:
# Filter odd-indexed elements
data = [5, 10, 15, 20, 25]

filtered = data[1::2]

print(filtered)

[10, 20]


In [ ]:
# Slicing multi-dimensional arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

print(" ------- ---------- ----------- ")

# :2 --> selects the first two rows
# 1: --> selects all columns starting from index one or second column
sub_matrix = matrix[:2, 1:]

print(sub_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 ------- ---------- ----------- 
[[2 3]
 [5 6]]
